language: python
sudo: false
services: docker
dist: trusty

before_script:
    - travis_retry timeout 120 docker pull fenicsproject/stable
    - docker run -itd --name dock -v $(pwd):/home/fenics/shared fenicsproject/stable

script:
    - docker exec dock bash -c "pip3 install --user hypothesis"
    - docker exec dock bash -c "cd shared/tests && python3 -m unittest discover"
