language: python
sudo: false
services: docker
dist: trusty

before_script:
    - travis_retry timeout 120 docker pull fenicsproject/stable
    - docker run -itd --name dock -v $(pwd):/home/fenics/shared fenicsproject/stable

script:
    - docker exec dock bash -c "pip3 install --no-cache-dir hypothesis tqdm"
    - docker exec dock bash -c "pip3 install --no-cache-dir ."
    - docker exec dock bash -c "python3 -m unittest discover -v"
