version: 2
jobs:
  build:
    docker:
      - image: fenicsproject/stable
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
              pip3 install --user hypothesis tqdm
              cd tests && python3 -m unittest discover -v
