version: 2
jobs:
  build:
    docker:
      - image: quay.io/fenicsproject/stable
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
              pip3 install --no-cache-dir hypothesis tqdm
              pip3 install --no-cache-dir .
              python3 -m unittest discover -v -s tests
